const express = require("express");
const router = express.Router();
const {CityController} = require("../../controllers") ;
const {CityMiddlewares} = require("../../middlewares") ;
router.post("/",CityMiddlewares.validateCreateRequest,CityController.createCity) ;
router.delete("/:id",CityController.deleteCity) ;
router.get("/:id",CityController.getCity) ;
router.get("/",CityController.getCities) ;
router.patch("/:id",CityController.updateCity) ;
module.exports = router ;